import { TourPackage, FeedbackReview, GalleryItem } from './types';

export const COMPANY_INFO = {
  name: "Sky Quest Holidays",
  tagline: "Explore Beyond Horizons",
  phone: "+91 73387 10611",
  whatsapp: "917338710611",
  email: "skyquestholidays@gmail.com",
  address: "Namakkal, Tamil Nadu - 627015",
  rating: 4.9,
  reviewsCount: "500+",
  yearsOfExperience: 8,
  govtRegNumber: "TN/NKL/TOUR/2020/4891"
};

export const CATEGORIES = [
  { id: "all", name: "✨ All Destinations", icon: "✨" },
  { id: "tamilnadu", name: "🛕 Tamil Nadu", icon: "🛕" },
  { id: "kerala", name: "🌴 Kerala", icon: "🌴" },
  { id: "karnataka", name: "🌄 Karnataka", icon: "🌄" },
  { id: "honeymoon", name: "❤️ Honeymoon", icon: "❤️" },
  { id: "college", name: "🎓 College IV", icon: "🎓" },
  { id: "international", name: "✈️ International", icon: "✈️" }
];

export const INITIAL_PACKAGES: TourPackage[] = [
  // ==================== KERALA ====================
  {
    id: "cochin-munnar",
    name: "Cochin – Munnar",
    title: "Cochin – Munnar Tea Hills Retreat",
    state: "🌴 Kerala",
    badge: "Popular",
    price: "₹4,999",
    originalPrice: "₹6,999",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80",
    desc: "Breathtaking tea gardens, misty hilltops, waterfalls, and tea factory tour.",
    location: "Munnar, Kerala",
    placesToVisit: ["Eravikulam National Park", "Mattupetty Dam", "Echo Point", "Top Station", "Tea Museum"],
    inclusions: ["3-Star Resort Stay", "Daily Breakfast", "Sightseeing Private Cab"],
    exclusions: ["Entry Tickets to Parks"],
    category: "kerala",
    featured: true
  },
  {
    id: "cochin-vagamon",
    name: "Cochin – Vagamon",
    title: "Cochin – Vagamon Pine Hills Tour",
    state: "🌴 Kerala",
    badge: "Scenic",
    price: "₹5,499",
    originalPrice: "₹7,500",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
    desc: "Explore pine forests, green meadows, and misty hills of Vagamon.",
    location: "Vagamon, Kerala",
    placesToVisit: ["Vagamon Pine Forest", "Vagamon Meadows", "Kurisumala", "Vagamon Lake"],
    inclusions: ["Deluxe Hotel Stay", "Daily Breakfast", "Private AC Cab for Sightseeing"],
    exclusions: ["Personal Expenses"],
    category: "kerala"
  },
  {
    id: "cochin-marayoor",
    name: "Cochin – Marayoor",
    title: "Cochin – Marayoor Sandalwood Forests",
    state: "🌴 Kerala",
    badge: "Nature",
    price: "₹5,999",
    originalPrice: "₹8,000",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
    desc: "Natural sandalwood forests, dolmens, sugarcane farms and waterfalls in Marayoor.",
    location: "Marayoor, Kerala",
    placesToVisit: ["Sandalwood Forest", "Muniyara Dolmens", "Lakkam Waterfalls", "Thuvanam Waterfalls"],
    inclusions: ["Nature Resort Stay", "Daily Breakfast", "Private AC Cab Sightseeing"],
    exclusions: ["Personal purchases"],
    category: "kerala"
  },
  {
    id: "cochin-wonderla",
    name: "Cochin – Wonderla",
    title: "Cochin – Wonderla Amusement Park",
    state: "🌴 Kerala",
    badge: "Fun",
    price: "₹3,999",
    originalPrice: "₹5,500",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80",
    desc: "Thrilling dry and wet water rides with entry passes to Wonderla Kochi.",
    location: "Kochi, Kerala",
    placesToVisit: ["Wonderla Amusement Park", "Lulu Mall Kochi", "Marine Drive"],
    inclusions: ["3-Star Hotel Stay", "Daily Breakfast", "Wonderla Entry Tickets", "Cab Transfers"],
    exclusions: ["Food inside park"],
    category: "kerala"
  },
  {
    id: "cochin-alappuzha",
    name: "Cochin – Alappuzha",
    title: "Cochin – Alappuzha Houseboat Cruise",
    state: "🌴 Kerala",
    badge: "Backwaters",
    price: "₹6,999",
    originalPrice: "₹9,500",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
    desc: "Private luxury houseboat cruise through serene backwaters with traditional Kerala buffet meals.",
    location: "Alappuzha, Kerala",
    placesToVisit: ["Alleppey Backwaters", "Vembanad Lake", "Alappuzha Beach", "Lighthouse"],
    inclusions: ["Private Houseboat Cruise", "All Meals (Lunch, Dinner, Breakfast)", "Welcome Drink"],
    exclusions: ["Canoeing rides"],
    category: "kerala",
    featured: true
  },
  {
    id: "cochin-varkala",
    name: "Cochin – Varkala",
    title: "Cochin – Varkala Cliff Beach Gateway",
    state: "🌴 Kerala",
    badge: "Beach",
    price: "₹5,999",
    originalPrice: "₹7,999",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
    desc: "Red laterite cliffs facing the Arabian Sea, golden sands, Janardhana temple & cafes.",
    location: "Varkala, Kerala",
    placesToVisit: ["Varkala Cliff", "Papanasam Beach", "Kappil Beach", "Janardhana Swamy Temple"],
    inclusions: ["Cliff View Hotel Stay", "Daily Breakfast", "Private Sightseeing Cab"],
    exclusions: ["Water sports"],
    category: "kerala"
  },
  {
    id: "cochin-wayanad",
    name: "Cochin – Wayanad",
    title: "Cochin – Wayanad Wildlife & Nature",
    state: "🌴 Kerala",
    badge: "Wildlife",
    price: "₹5,999",
    originalPrice: "₹8,200",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=800&q=80",
    desc: "Explore lush green caves, bamboo rafting, dams and cascading waterfalls.",
    location: "Wayanad, Kerala",
    placesToVisit: ["Edakkal Caves", "Banasura Sagar Dam", "Soochipara Falls", "Chembra Peak"],
    inclusions: ["Valley View Resort", "Breakfast & Dinner", "Sightseeing Cab"],
    exclusions: ["Forest trek fee"],
    category: "kerala"
  },
  {
    id: "marayoor-munnar",
    name: "Marayoor – Munnar",
    title: "Marayoor – Munnar Forest & Tea Hills",
    state: "🌴 Kerala",
    badge: "Heritage",
    price: "₹5,499",
    originalPrice: "₹7,500",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80",
    desc: "Ancient dolmens, natural sandalwood forest, and top tea garden viewpoints in Munnar.",
    location: "Marayoor & Munnar, Kerala",
    placesToVisit: ["Muniyara Dolmens", "Sandalwood Reserves", "Eravikulam National Park", "Mattupetty Dam"],
    inclusions: ["Resort Stay", "Daily Breakfast", "Private AC Cab"],
    exclusions: ["Entry passes"],
    category: "kerala"
  },
  {
    id: "varkala-munnar",
    name: "Varkala – Munnar",
    title: "Varkala – Munnar Cliff & Mist Combo",
    state: "🌴 Kerala",
    badge: "Scenic",
    price: "₹6,499",
    originalPrice: "₹8,800",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    desc: "The perfect contrast: red beach cliffs of Varkala and the misty tea hilltops of Munnar.",
    location: "Varkala & Munnar, Kerala",
    placesToVisit: ["Varkala Cliff Beach", "Munnar Tea Plantations", "Echo Point", "Lakkam Falls"],
    inclusions: ["Deluxe Hotel Stays", "Daily Breakfast", "Sightseeing Cab"],
    exclusions: ["Personal expenses"],
    category: "kerala"
  },
  {
    id: "varkala-vagamon",
    name: "Varkala – Vagamon",
    title: "Varkala – Vagamon Coast & Pine Hills",
    state: "🌴 Kerala",
    badge: "Relaxing",
    price: "₹5,999",
    originalPrice: "₹8,000",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
    desc: "Unwind at Varkala beach cliffs followed by pine forest walks and green meadows of Vagamon.",
    location: "Varkala & Vagamon, Kerala",
    placesToVisit: ["Varkala Beach", "Vagamon Pine Forest", "Vagamon Meadows", "Kurisumala"],
    inclusions: ["Resort Stays", "Daily Breakfast", "Private Cab for Transfers"],
    exclusions: ["Personal expenses"],
    category: "kerala"
  },

  // ==================== KARNATAKA ====================
  {
    id: "bangalore-mysore",
    name: "Bangalore – Mysore",
    title: "Bangalore – Mysore Royal Heritage Tour",
    state: "🌄 Karnataka",
    badge: "Royal",
    price: "₹4,999",
    originalPrice: "₹6,999",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=80",
    desc: "Grand Mysore Palace, Chamundi Hill, Brindavan Gardens illumination & Srirangapatna.",
    location: "Mysore, Karnataka",
    placesToVisit: ["Mysuru Palace", "Chamundeshwari Temple", "Brindavan Gardens", "St. Philomena's Cathedral"],
    inclusions: ["3-Star Hotel Stay", "Daily Breakfast", "Private AC Cab from Bangalore"],
    exclusions: ["Palace entrance tickets"],
    category: "karnataka"
  },
  {
    id: "bangalore-coorg",
    name: "Bangalore – Coorg",
    title: "Bangalore – Coorg Coffee Trail Tour",
    state: "🌄 Karnataka",
    badge: "Coffee Trail",
    price: "₹5,499",
    originalPrice: "₹7,800",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?auto=format&fit=crop&w=800&q=80",
    desc: "Scotland of India: Coffee plantation walk, Abbey Falls, Raja's Seat & Golden Temple.",
    location: "Madikeri, Coorg, Karnataka",
    placesToVisit: ["Abbey Falls", "Raja's Seat", "Dubare Elephant Camp", "Namdroling Golden Temple", "Talacauvery"],
    inclusions: ["Plantation Resort Stay", "Buffet Breakfast", "Private Sightseeing Car"],
    exclusions: ["Elephant activity fees"],
    category: "karnataka",
    featured: true
  },
  {
    id: "bangalore-chikmagalore",
    name: "Bangalore – Chikmagalore",
    title: "Bangalore – Chikmagalur Peak & Coffee Hills",
    state: "🌄 Karnataka",
    badge: "Hills",
    price: "₹5,499",
    originalPrice: "₹7,500",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=800&q=80",
    desc: "Mullayanagiri (highest peak in Karnataka), Baba Budangiri, Hebbe Falls and lush coffee estates.",
    location: "Chikmagalur, Karnataka",
    placesToVisit: ["Mullayanagiri Peak", "Baba Budangiri", "Hebbe Falls", "Jhari Waterfalls", "Coffee Museum"],
    inclusions: ["Hillview Hotel", "Daily Breakfast", "Private Cab Sightseeing"],
    exclusions: ["Jeep hire for peaks"],
    category: "karnataka"
  },
  {
    id: "mysore-coorg",
    name: "Mysore – Coorg",
    title: "Mysore – Coorg Heritage & Hill Retreat",
    state: "🌄 Karnataka",
    badge: "Heritage",
    price: "₹5,999",
    originalPrice: "₹8,200",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?auto=format&fit=crop&w=800&q=80",
    desc: "Combine royal architecture of Mysore with lush green plantations of Coorg.",
    location: "Mysore & Coorg, Karnataka",
    placesToVisit: ["Mysore Palace", "Abbey Falls", "Golden Temple Bylakuppe", "Raja's Seat"],
    inclusions: ["Resort Stay", "Daily Breakfast", "Private Cab Transfers"],
    exclusions: ["Monuments entry"],
    category: "karnataka"
  },
  {
    id: "mysore-chikmagalore",
    name: "Mysore – Chikmagalore",
    title: "Mysore – Chikmagalur Nature Circuit",
    state: "🌄 Karnataka",
    badge: "Nature",
    price: "₹5,999",
    originalPrice: "₹8,200",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=800&q=80",
    desc: "Explore historic Chamundi hills and head to misty valleys of Chikmagalur.",
    location: "Mysore & Chikmagalur, Karnataka",
    placesToVisit: ["Chamundi Temple", "Mullayanagiri Peak", "Baba Budangiri", "Coffee Estates"],
    inclusions: ["Hotel Stay", "Daily Breakfast", "Sightseeing Cab"],
    exclusions: ["Personal expenses"],
    category: "karnataka"
  },
  {
    id: "coorg-chikmagalore",
    name: "Coorg – Chikmagalore",
    title: "Coorg – Chikmagalur Double Coffee Hills Combo",
    state: "🌄 Karnataka",
    badge: "Combo",
    price: "₹6,999",
    originalPrice: "₹9,500",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?auto=format&fit=crop&w=800&q=80",
    desc: "Experience both premier coffee hubs of Karnataka: Coorg and Chikmagalur.",
    location: "Coorg & Chikmagalur, Karnataka",
    placesToVisit: ["Abbey Falls", "Golden Temple", "Mullayanagiri Peak", "Hebbe Falls"],
    inclusions: ["Plantation Resort", "Daily Breakfast", "Private AC Cab"],
    exclusions: ["Jeep safari"],
    category: "karnataka"
  },

  // ==================== TAMIL NADU ====================
  {
    id: "ooty",
    name: "Ooty",
    title: "Ooty Queen of Hill Stations Tour",
    state: "🛕 Tamil Nadu",
    badge: "Popular",
    price: "₹4,499",
    originalPrice: "₹6,500",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    desc: "Botanical gardens, Ooty boathouse, Doddabetta Peak, Tea Factory & Sim's Park Coonoor.",
    location: "Ooty, Tamil Nadu",
    placesToVisit: ["Ooty Lake", "Botanical Garden", "Doddabetta Peak", "Rose Garden", "Coonoor Tea Gardens"],
    inclusions: ["Cozy Resort Stay", "Complimentary Breakfast", "Private Sightseeing Vehicle"],
    exclusions: ["Toy train tickets"],
    category: "tamilnadu",
    featured: true
  },
  {
    id: "kodaikanal",
    name: "Kodaikanal",
    title: "Kodaikanal Princess of Hills Tour",
    state: "🛕 Tamil Nadu",
    badge: "Scenic",
    price: "₹4,999",
    originalPrice: "₹6,999",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    desc: "Star-shaped Kodai Lake, Pillar Rocks, Coaker's Walk, Pine Forest & Silver Cascade.",
    location: "Kodaikanal, Tamil Nadu",
    placesToVisit: ["Kodai Lake", "Pillar Rocks", "Coaker's Walk", "Pine Forest", "Bryant Park", "Guna Caves"],
    inclusions: ["Hilltop View Hotel", "Daily Breakfast", "Sightseeing Cab"],
    exclusions: ["Boating fees"],
    category: "tamilnadu"
  },
  {
    id: "rameswaram",
    name: "Rameswaram",
    title: "Rameswaram Holy Island & Dhanushkodi",
    state: "🛕 Tamil Nadu",
    badge: "Spiritual",
    price: "₹4,999",
    originalPrice: "₹6,800",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    desc: "Ramanathaswamy Temple 22 Theerthams, Pamban Sea Bridge, Dhanushkodi Ghost Town & APJ Abdul Kalam Memorial.",
    location: "Rameswaram, Tamil Nadu",
    placesToVisit: ["Ramanathaswamy Temple", "Pamban Bridge", "Dhanushkodi Point", "Kalam Memorial", "Agni Theertham"],
    inclusions: ["3-Star Hotel Stay", "Daily Breakfast", "Private AC Cab for Full Tour"],
    exclusions: ["Temple pooja tickets"],
    category: "tamilnadu"
  },
  {
    id: "madurai",
    name: "Madurai",
    title: "Madurai Temple City & Heritage Tour",
    state: "🛕 Tamil Nadu",
    badge: "Heritage",
    price: "₹3,999",
    originalPrice: "₹5,500",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    desc: "Meenakshi Amman Temple, Thirumalai Nayakkar Mahal, Gandhi Memorial & authentic food trail.",
    location: "Madurai, Tamil Nadu",
    placesToVisit: ["Meenakshi Amman Temple", "Thirumalai Nayakar Palace", "Alagar Kovil", "Gandhi Museum"],
    inclusions: ["Hotel Stay", "Daily Breakfast", "Private AC Cab Sightseeing"],
    exclusions: ["Personal expenses"],
    category: "tamilnadu"
  },
  {
    id: "mahabalipuram",
    name: "Mahabalipuram",
    title: "Mahabalipuram UNESCO Shore Temple & Coastal Tour",
    state: "🛕 Tamil Nadu",
    badge: "Historical",
    price: "₹3,999",
    originalPrice: "₹5,500",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    desc: "Shore Temple, Pancha Rathas, Arjuna's Penance, Krishna's Butter Ball and beach resorts.",
    location: "Mahabalipuram, Tamil Nadu",
    placesToVisit: ["Shore Temple", "Pancha Rathas", "Arjuna's Penance", "Krishna's Butterball", "Mahabalipuram Beach"],
    inclusions: ["Beach Resort Stay", "Daily Breakfast", "AC Cab Transfers"],
    exclusions: ["Monument entry fee"],
    category: "tamilnadu"
  },
  {
    id: "kanyakumari",
    name: "Kanyakumari",
    title: "Kanyakumari Sunset & Vivekananda Rock Tour",
    state: "🛕 Tamil Nadu",
    badge: "Ocean Tip",
    price: "₹4,999",
    originalPrice: "₹6,800",
    duration: "2D | 1N",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    desc: "Triveni Sangam confluence of 3 oceans, Vivekananda Rock Memorial, Thiruvalluvar Statue & Sunset viewpoint.",
    location: "Kanyakumari, Tamil Nadu",
    placesToVisit: ["Vivekananda Rock Memorial", "Thiruvalluvar Statue", "Sunset View Point", "Kanyakumari Temple", "Gandhi Memorial"],
    inclusions: ["Sea View Hotel Stay", "Daily Breakfast", "Private Cab for Tour"],
    exclusions: ["Ferry tickets"],
    category: "tamilnadu"
  }
];

export const INITIAL_FEEDBACK: FeedbackReview[] = [
  {
    id: "rev-1",
    name: "Karthik R.",
    location: "Chennai",
    rating: 5,
    comment: "Our Munnar family trip arranged by Sky Quest was unbelievable! The driver was very polite, hotel had misty mountain views, and the pricing was super genuine. Highly recommended!",
    tour: "Cochin – Munnar 2D/1N"
  },
  {
    id: "rev-2",
    name: "Priya & Vignesh",
    location: "Coimbatore",
    rating: 5,
    comment: "Booked our honeymoon to Alleppey houseboat and Munnar. The candle light dinner and flower decoration were magical. 10/10 service by Jeeva and team!",
    tour: "Munnar & Alleppey Honeymoon"
  },
  {
    id: "rev-3",
    name: "Suresh Kumar",
    location: "Salem",
    rating: 5,
    comment: "Organized our college IV to Goa (45 students). Everything from luxury bus, beach resort, buffet food, and party cruise was perfectly handled without a single glitch.",
    tour: "Goa College IV Tour"
  }
];

export const INITIAL_GALLERY: GalleryItem[] = [
  {
    id: "gal-1",
    title: "Tea Plantations Munnar",
    location: "Munnar, Kerala",
    category: "Kerala",
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "gal-2",
    title: "Alleppey Backwaters Houseboat",
    location: "Alappuzha, Kerala",
    category: "Kerala",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "gal-3",
    title: "Ooty Botanical Garden",
    location: "Ooty, Tamil Nadu",
    category: "Tamil Nadu",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "gal-4",
    title: "Kodaikanal Lake Mist",
    location: "Kodaikanal, Tamil Nadu",
    category: "Tamil Nadu",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "gal-5",
    title: "Coorg Coffee Hills",
    location: "Coorg, Karnataka",
    category: "Karnataka",
    image: "https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "gal-6",
    title: "Goa Sunset Beach",
    location: "Goa",
    category: "Goa",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80"
  }
];
