const SKY_QUEST_DATA = {
  company: {
    name: "Sky Quest Holidays",
    phone: "+91 73387 10611",
    whatsapp: "917338710611",
    email: "skyquestholidays@gmail.com",
    address: "Namakkal, Tamil Nadu - 627015"
  },

  categories: [
    { id: "all", name: "All Packages", icon: "🌍" },
    { id: "tamilnadu", name: "Tamil Nadu", icon: "🏛️" },
    { id: "kerala", name: "Kerala", icon: "🌴" },
    { id: "karnataka", name: "Karnataka", icon: "⛰️" },
    { id: "honeymoon", name: "Honeymoon Specials", icon: "❤️" },
    { id: "family", name: "Family Vacations", icon: "👨‍👩‍👧‍👦" },
    { id: "college", name: "College IV & Groups", icon: "🎓" },
    { id: "international", name: "International Tours", icon: "✈️" }
  ],

  packages: [
    // --- Kerala ---
    {
      id: 1,
      name: "Cochin – Munnar",
      title: "Cochin – Munnar Tea Hills Retreat",
      state: "Kerala",
      badge: "Popular",
      price: "₹4,999",
      originalPrice: "₹6,999",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80",
      desc: "Breathtaking tea gardens, misty hilltops, waterfalls, and tea factory tour.",
      location: "Munnar, Kerala",
      placesToVisit: ["Eravikulam National Park", "Mattupetty Dam", "Echo Point", "Top Station", "Tea Museum"],
      inclusions: ["3-Star Resort Stay", "Daily Breakfast", "Sightseeing Private Cab"],
      exclusions: ["Entry Tickets to Parks"],
      category: "Kerala"
    },
    {
      id: 2,
      name: "Cochin – Vagamon",
      title: "Cochin – Vagamon Pine Hills Tour",
      state: "Kerala",
      badge: "Scenic",
      price: "₹5,499",
      originalPrice: "₹7,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
      desc: "Explore pine forests, green meadows, and misty hills of Vagamon.",
      location: "Vagamon, Kerala",
      placesToVisit: ["Vagamon Pine Forest", "Vagamon Meadows", "Kurisumala", "Vagamon Lake"],
      inclusions: ["Deluxe Hotel Stay", "Daily Breakfast", "Private AC Cab for Sightseeing"],
      exclusions: ["Personal Expenses"],
      category: "Kerala"
    },
    {
      id: 3,
      name: "Cochin – Marayoor",
      title: "Cochin – Marayoor Sandalwood Forests",
      state: "Kerala",
      badge: "Nature",
      price: "₹5,999",
      originalPrice: "₹8,000",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
      desc: "Visit natural sandalwood forests, dolmens, and sugarcane farms in Marayoor.",
      location: "Marayoor, Kerala",
      placesToVisit: ["Sandalwood Forest", "Muniyara Dolmens", "Lakkam Waterfalls", "Thuvanam Waterfalls"],
      inclusions: ["Nature Resort Stay", "Daily Breakfast", "Private AC Cab Sightseeing"],
      exclusions: ["Personal purchases"],
      category: "Kerala"
    },
    {
      id: 4,
      name: "Cochin – Wonderla",
      title: "Cochin – Wonderla Theme Park Fun",
      state: "Kerala",
      badge: "Fun",
      price: "₹3,999",
      originalPrice: "₹5,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80",
      desc: "Enjoy thrilling dry & wet rides with entry passes to Wonderla Kochi.",
      location: "Kochi, Kerala",
      placesToVisit: ["Wonderla Amusement Park", "Lulu Mall Kochi", "Marine Drive"],
      inclusions: ["3-Star Hotel Stay", "Daily Breakfast", "Wonderla Entry Tickets", "Cab Transfers"],
      exclusions: ["Food inside theme park"],
      category: "Kerala"
    },
    {
      id: 5,
      name: "Cochin – Alappuzha",
      title: "Cochin – Alappuzha Houseboat Cruise",
      state: "Kerala",
      badge: "Backwaters",
      price: "₹6,999",
      originalPrice: "₹9,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80",
      desc: "Stay in a traditional backwater houseboat and cruise through scenic canals.",
      location: "Alappuzha, Kerala",
      placesToVisit: ["Alappuzha Backwaters", "Vembanad Lake", "Alappuzha Beach", "Pathiramanal Island"],
      inclusions: ["Private Houseboat Stay", "All Meals (Breakfast, Lunch, Dinner)", "Backwater Cruise"],
      exclusions: ["Travel to Cochin"],
      category: "Kerala"
    },
    {
      id: 6,
      name: "Cochin – Varkala",
      title: "Cochin – Varkala Cliff Beach Holiday",
      state: "Kerala",
      badge: "Beach",
      price: "₹5,999",
      originalPrice: "₹8,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
      desc: "Relax at Varkala Cliff Beach, explore cafes, and visit Janardhana Temple.",
      location: "Varkala Cliff, Kerala",
      placesToVisit: ["Varkala Beach", "Varkala Cliff", "Janardhana Swami Temple", "Anjengo Fort"],
      inclusions: ["Cliff-side Resort Stay", "Daily Breakfast", "Private AC Cab transfers"],
      exclusions: ["Water sports"],
      category: "Kerala"
    },
    {
      id: 7,
      name: "Cochin – Wayanad",
      title: "Cochin – Wayanad Rainforest Hills",
      state: "Kerala",
      badge: "Wildlife",
      price: "₹6,499",
      originalPrice: "₹8,999",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
      desc: "Experience misty hills, Banasura Sagar dam, and Edakkal caves.",
      location: "Wayanad, Kerala",
      placesToVisit: ["Banasura Sagar Dam", "Edakkal Caves", "Pookode Lake", "Lakkidi View Point"],
      inclusions: ["Rainforest Resort Stay", "Daily Breakfast", "Private Sightseeing Cab"],
      exclusions: ["Safari/Activity tickets"],
      category: "Kerala"
    },
    {
      id: 8,
      name: "Marayoor – Munnar",
      title: "Marayoor & Munnar Tea & Sandalwood Combo",
      state: "Kerala",
      badge: "Heritage",
      price: "₹6,999",
      originalPrice: "₹9,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=800&q=80",
      desc: "Combines sandalwood forests and dolmens with scenic tea plantations.",
      location: "Marayoor & Munnar, Kerala",
      placesToVisit: ["Munnar Tea Gardens", "Sandalwood Forests", "Muniyara Dolmens", "Lakkam Falls"],
      inclusions: ["Resort Stay", "Daily Breakfast", "AC Cab Sightseeing"],
      exclusions: ["Personal expenses"],
      category: "Kerala"
    },
    {
      id: 9,
      name: "Varkala – Munnar",
      title: "Varkala Cliff Beach & Munnar Hills Combo",
      state: "Kerala",
      badge: "Scenic",
      price: "₹7,999",
      originalPrice: "₹10,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80",
      desc: "Experience the unique combination of sunny beaches and misty mountains.",
      location: "Varkala & Munnar, Kerala",
      placesToVisit: ["Varkala Cliff Beach", "Munnar Tea Gardens", "Mattupetty Dam", "Echo Point"],
      inclusions: ["Hotel Stays", "Daily Breakfast", "Private AC Cab Transfers"],
      exclusions: ["Activity fees"],
      category: "Kerala"
    },
    {
      id: 10,
      name: "Varkala – Vagamon",
      title: "Varkala Cliff Beach & Vagamon Meadows Combo",
      state: "Kerala",
      badge: "Relaxing",
      price: "₹7,499",
      originalPrice: "₹9,999",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
      desc: "Relax at sandy beaches and enjoy green meadows and pine forests.",
      location: "Varkala & Vagamon, Kerala",
      placesToVisit: ["Varkala Beach", "Vagamon Pine Forest", "Vagamon Meadows", "Kurisumala"],
      inclusions: ["Hotel & Resort Stays", "Daily Breakfast", "Private AC Cab Sightseeing"],
      exclusions: ["Meals other than breakfast"],
      category: "Kerala"
    },

    // --- Karnataka ---
    {
      id: 11,
      name: "Bangalore – Mysore",
      title: "Bangalore – Mysore Royal Heritage",
      state: "Karnataka",
      badge: "Royal",
      price: "₹4,499",
      originalPrice: "₹6,000",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      desc: "Explore Mysore Palace, Chamundi Hills, and Brindavan Gardens.",
      location: "Mysore, Karnataka",
      placesToVisit: ["Mysore Palace", "Chamundi Hills", "Brindavan Gardens", "Srirangapatna"],
      inclusions: ["Deluxe Hotel Stay", "Daily Breakfast", "Sightseeing Private Cab"],
      exclusions: ["Entry tickets"],
      category: "Karnataka"
    },
    {
      id: 12,
      name: "Bangalore – Coorg",
      title: "Bangalore – Coorg Coffee Estates",
      state: "Karnataka",
      badge: "Coffee Trail",
      price: "₹5,499",
      originalPrice: "₹7,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
      desc: "Misty coffee estates, Abbey Falls, and Golden Temple at Kushalnagar.",
      location: "Coorg, Karnataka",
      placesToVisit: ["Abbey Falls", "Golden Temple Bypass", "Raja Seat", "Dubare Elephant Camp"],
      inclusions: ["Estate Stay", "Daily Breakfast", "Sightseeing Cab"],
      exclusions: ["Activity charges"],
      category: "Karnataka"
    },
    {
      id: 13,
      name: "Bangalore – Chikmagalore",
      title: "Bangalore – Chikmagalore Coffee Hills",
      state: "Karnataka",
      badge: "Hills",
      price: "₹5,999",
      originalPrice: "₹8,000",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      desc: "Trek Mullayanagiri Peak and visit scenic coffee plantation hills.",
      location: "Chikmagalur, Karnataka",
      placesToVisit: ["Mullayanagiri Peak", "Baba Budangiri Hills", "Hebbe Waterfalls", "Jhari Waterfalls"],
      inclusions: ["Estate Cottage Stay", "Daily Breakfast & Dinner", "Sightseeing Jeep Drive"],
      exclusions: ["Personal expenses"],
      category: "Karnataka"
    },
    {
      id: 14,
      name: "Mysore – Coorg",
      title: "Mysore Heritage & Coorg Hills Combo",
      state: "Karnataka",
      badge: "Heritage",
      price: "₹6,499",
      originalPrice: "₹8,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
      desc: "Combines royal palace heritage with mist-covered coffee plantation walks.",
      location: "Mysore & Coorg, Karnataka",
      placesToVisit: ["Mysore Palace", "Abbey Falls", "Dubare Elephant Camp", "Raja Seat"],
      inclusions: ["Deluxe Hotel Stay", "Daily Breakfast", "Sightseeing AC Cab"],
      exclusions: ["Entry passes"],
      category: "Karnataka"
    },
    {
      id: 15,
      name: "Mysore – Chikmagalore",
      title: "Mysore Palace & Chikmagalur Coffee Gardens",
      state: "Karnataka",
      badge: "Nature",
      price: "₹6,999",
      originalPrice: "₹9,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      desc: "Experience royal palaces and then relax in scenic green hills.",
      location: "Mysore & Chikmagalur, Karnataka",
      placesToVisit: ["Mysore Palace", "Mullayanagiri Peak", "Baba Budangiri", "Hebbe Falls"],
      inclusions: ["Resort cottage stays", "Daily Breakfast & Dinner", "AC Cab sightseeing"],
      exclusions: ["Personal expenses"],
      category: "Karnataka"
    },
    {
      id: 16,
      name: "Coorg – Chikmagalore",
      title: "Coorg & Chikmagalur Ultimate Coffee Tour",
      state: "Karnataka",
      badge: "Combo",
      price: "₹7,999",
      originalPrice: "₹10,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
      desc: "Explore the two premier coffee hill stations of Karnataka.",
      location: "Coorg & Chikmagalur, Karnataka",
      placesToVisit: ["Abbey Falls", "Golden Temple", "Mullayanagiri Peak", "Baba Budangiri"],
      inclusions: ["Deluxe Resort Stays", "Daily Breakfast", "Private AC Cab Transfers"],
      exclusions: ["Meals other than breakfast"],
      category: "Karnataka"
    },

    // --- Tamil Nadu ---
    {
      id: 17,
      name: "Ooty",
      title: "Ooty Misty Hills Tour",
      state: "Tamil Nadu",
      badge: "Popular",
      price: "₹3,999",
      originalPrice: "₹5,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
      desc: "Mist-covered peaks, botanical gardens, pine forests, and lake boating.",
      location: "Ooty, Tamil Nadu",
      placesToVisit: ["Doddabetta Peak", "Botanical Garden", "Ooty Lake", "Pine Forest", "Pykara Waterfalls"],
      inclusions: ["Deluxe Hotel Stay", "Daily Breakfast", "Sightseeing Cab", "Driver Batta & Tolls"],
      exclusions: ["Toy Train Tickets", "Boating Fees"],
      category: "Tamil Nadu"
    },
    {
      id: 18,
      name: "Kodaikanal",
      title: "Kodaikanal Misty Lake Tour",
      state: "Tamil Nadu",
      badge: "Scenic",
      price: "₹3,999",
      originalPrice: "₹5,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
      desc: "Pillar rocks, pine forests, Coakers Walk, and lake boating.",
      location: "Kodaikanal, Tamil Nadu",
      placesToVisit: ["Kodaikanal Lake", "Pillar Rocks", "Pine Forest", "Coakers Walk", "Guna Caves"],
      inclusions: ["Deluxe Hotel Stay", "Daily Breakfast & Dinner", "Sightseeing Private Cab", "Driver Batta"],
      exclusions: ["Boating Tickets"],
      category: "Tamil Nadu"
    },
    {
      id: 19,
      name: "Rameswaram",
      title: "Rameswaram Island Tour",
      state: "Tamil Nadu",
      badge: "Spiritual",
      price: "₹3,499",
      originalPrice: "₹4,999",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
      desc: "Ramanathaswamy temple, Pamban bridge, and holy Dhanushkodi beach.",
      location: "Rameswaram, Tamil Nadu",
      placesToVisit: ["Ramanathaswamy Temple", "Pamban Bridge", "Dhanushkodi Beach", "Agni Theertham"],
      inclusions: ["Deluxe Hotel Stay", "Daily Breakfast", "Sightseeing Cab", "Driver Batta & Tolls"],
      exclusions: ["Temple Special Darshan tickets"],
      category: "Tamil Nadu"
    },
    {
      id: 20,
      name: "Madurai",
      title: "Madurai Temple City Heritage",
      state: "Tamil Nadu",
      badge: "Heritage",
      price: "₹3,499",
      originalPrice: "₹4,999",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
      desc: "Explore historic Madurai Meenakshi Temple and Thirumalai Nayakar Palace.",
      location: "Madurai, Tamil Nadu",
      placesToVisit: ["Meenakshi Amman Temple", "Thirumalai Nayakar Palace", "Alagar Kovil", "Gandhi Memorial Museum"],
      inclusions: ["Deluxe Hotel Stay", "Daily Breakfast", "Sightseeing Private Cab"],
      exclusions: ["Temple Entry charges"],
      category: "Tamil Nadu"
    },
    {
      id: 21,
      name: "Mahabalipuram",
      title: "Mahabalipuram Shore Temples Tour",
      state: "Tamil Nadu",
      badge: "Historical",
      price: "₹3,499",
      originalPrice: "₹4,999",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
      desc: "Shore temples, Pancha Rathas, and Arjuna's Penance stone sculptures.",
      location: "Mahabalipuram, Tamil Nadu",
      placesToVisit: ["Shore Temple", "Pancha Rathas", "Arjuna's Penance", "Krishna's Butterball"],
      inclusions: ["Beach Resort Stay", "Daily Breakfast", "Private AC Cab sightseeing"],
      exclusions: ["Entry passes to heritage structures"],
      category: "Tamil Nadu"
    },
    {
      id: 22,
      name: "Kanyakumari",
      title: "Kanyakumari Sunrise Ocean Tip",
      state: "Tamil Nadu",
      badge: "Ocean Tip",
      price: "₹3,999",
      originalPrice: "₹5,500",
      duration: "2D | 1N",
      image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
      desc: "Vivekananda rock memorial, Thiruvalluvar statue, and sunrise/sunset ocean confluence.",
      location: "Kanyakumari, Tamil Nadu",
      placesToVisit: ["Vivekananda Rock Memorial", "Thiruvalluvar Statue", "Sunset View Point", "Kanyakumari Beach"],
      inclusions: ["Deluxe Hotel Stay", "Daily Breakfast", "Sightseeing Cab", "Driver Batta & Tolls"],
      exclusions: ["Ferry ride tickets"],
      category: "Tamil Nadu"
    }
  ],

  gallery: [],

  testimonials: [],

  videoStories: [],

  faqs: [
    { q: "What is the advance payment percentage required to book a trip?", a: "You only need to pay a nominal 20% to 30% advance to confirm your resort, vehicle, and flight/train seats. The remaining balance can be conveniently paid upon arrival or during your trip." },
    { q: "What is your trip cancellation and refund policy?", a: "We offer customer-friendly cancellation policies: 100% full refund on hotel/cab booking if cancelled 7+ days before the travel date. For unavoidable emergencies, we also allow free date rescheduling without any penalty." },
    { q: "Do you offer group discounts for College IV and large family trips?", a: "Yes! We offer special bulk discounts for groups of 15+ travelers. For College Industrial Visits (IV), we provide complimentary passes for staff coordinators, free DJ night setup, and official IV permission letters." },
    { q: "How do I book a customized tour with Sky Quest Holidays?", a: "Simply click on 'Chat on WhatsApp' or fill out our online enquiry form. Our tour specialist will get in touch with you within 15 minutes to craft your ideal customized itinerary!" },
    { q: "Do you specialize in College Industrial Visits (IV)?", a: "Yes! We have coordinated IV trips for over 300+ colleges across Tamil Nadu, Karnataka & Kerala with official IV letters, industrial plant access, DJ nights, and 100% student safety." },
    { q: "Can dietary preferences (Pure Veg / Jain / Non-Veg) be customized?", a: "Abolutely! We arrange authentic South Indian / North Indian meals catering to your exact dietary preferences (Pure Veg, Jain food, or Non-Veg) at hygienic rated restaurants." },
    { q: "What payment methods are accepted?", a: "We accept all major payment modes including UPI (GPay, PhonePe, Paytm), Net Banking, Credit/Debit Cards, and Direct Cash at our office." }
  ],

  blogs: []
};

if (typeof window !== 'undefined') {
  window.SKY_QUEST_DATA = SKY_QUEST_DATA;
}
